/* Automatically generated by ./configure -- do not edit */
#ifndef _CONFIG_H
#define _CONFIG_H

#define PACKAGE "ngat"
#define VERSION "0.1"
#define HAVE_STRLCPY 0
#define HAVE_EVENT_H 2
#define HAVE_REGEX_H 1
#define PREFIX "/usr/local"
#define BINDIR "/usr/local/bin"
#define SBINDIR "/usr/local/sbin"
#define LIBDIR "/usr/local/lib"
#define INCLUDEDIR "/usr/local/include"
#define DATADIR "/usr/local/share"
#define PKGDATADIR "/usr/local/share/ngat"
#define MANDIR "/usr/local/share/man"

#endif /* _CONFIG_H */
